#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Type of product Classification.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum product_productstructure
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductFamily = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductBundle = 3,
	}
	
	/// <summary>
	/// Type of product.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum product_producttypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesInventory = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MiscellaneousCharges = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Services = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FlatFees = 4,
	}
	
	/// <summary>
	/// Status of the product.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum product_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnderRevision = 3,
	}
	
	/// <summary>
	/// Reason for the status of the product.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum product_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Retired = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnderRevision = 3,
	}
	
	/// <summary>
	/// Information about products and their pricing information.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("product")]
	public partial class Product : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the product entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByExternalParty = "createdbyexternalparty";
			public const string CreatedByExternalPartyName = "createdbyexternalpartyname";
			public const string CreatedByExternalPartyYomiName = "createdbyexternalpartyyominame";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CurrentCost = "currentcost";
			public const string CurrentCost_Base = "currentcost_base";
			public const string DefaultUoMId = "defaultuomid";
			public const string DefaultUoMIdName = "defaultuomidname";
			public const string DefaultUoMScheduleId = "defaultuomscheduleid";
			public const string DefaultUoMScheduleIdName = "defaultuomscheduleidname";
			public const string Description = "description";
			public const string DMTImportState = "dmtimportstate";
			public const string EntityImage = "entityimage";
			public const string EntityImage_Timestamp = "entityimage_timestamp";
			public const string EntityImage_URL = "entityimage_url";
			public const string EntityImageId = "entityimageid";
			public const string ExchangeRate = "exchangerate";
			public const string HierarchyPath = "hierarchypath";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsKit = "iskit";
			public const string IsKitName = "iskitname";
			public const string IsReparented = "isreparented";
			public const string isreparentedName = "isreparentedname";
			public const string IsStockItem = "isstockitem";
			public const string IsStockItemName = "isstockitemname";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByExternalParty = "modifiedbyexternalparty";
			public const string ModifiedByExternalPartyName = "modifiedbyexternalpartyname";
			public const string ModifiedByExternalPartyYomiName = "modifiedbyexternalpartyyominame";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string msdyn_AlsoKnownAs = "msdyn_alsoknownas";
			public const string msdyn_ConvertToCustomerAsset = "msdyn_converttocustomerasset";
			public const string msdyn_converttocustomerassetName = "msdyn_converttocustomerassetname";
			public const string msdyn_DefaultVendor = "msdyn_defaultvendor";
			public const string msdyn_DefaultVendorName = "msdyn_defaultvendorname";
			public const string msdyn_DefaultVendorYomiName = "msdyn_defaultvendoryominame";
			public const string msdyn_FieldServiceProductType = "msdyn_fieldserviceproducttype";
			public const string msdyn_fieldserviceproducttypeName = "msdyn_fieldserviceproducttypename";
			public const string msdyn_gdproptout = "msdyn_gdproptout";
			public const string msdyn_gdproptoutName = "msdyn_gdproptoutname";
			public const string msdyn_PurchaseName = "msdyn_purchasename";
			public const string msdyn_scopes = "msdyn_scopes";
			public const string msdyn_Taxable = "msdyn_taxable";
			public const string msdyn_taxableName = "msdyn_taxablename";
			public const string msdyn_UPCCode = "msdyn_upccode";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string OrganizationIdName = "organizationidname";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string ParentProductId = "parentproductid";
			public const string ParentProductIdName = "parentproductidname";
			public const string Price = "price";
			public const string Price_Base = "price_base";
			public const string PriceLevelId = "pricelevelid";
			public const string PriceLevelIdName = "pricelevelidname";
			public const string ProcessId = "processid";
			public const string ProductId = "productid";
			public const string Id = "productid";
			public const string ProductNumber = "productnumber";
			public const string ProductStructure = "productstructure";
			public const string ProductStructureName = "productstructurename";
			public const string ProductTypeCode = "producttypecode";
			public const string ProductTypeCodeName = "producttypecodename";
			public const string ProductUrl = "producturl";
			public const string QuantityDecimal = "quantitydecimal";
			public const string QuantityOnHand = "quantityonhand";
			public const string Size = "size";
			public const string StageId = "stageid";
			public const string StandardCost = "standardcost";
			public const string StandardCost_Base = "standardcost_base";
			public const string StateCode = "statecode";
			public const string StateCodeName = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodeName = "statuscodename";
			public const string StockVolume = "stockvolume";
			public const string StockWeight = "stockweight";
			public const string SubjectId = "subjectid";
			public const string SubjectIdName = "subjectidname";
			public const string SupplierName = "suppliername";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string ValidFromDate = "validfromdate";
			public const string ValidToDate = "validtodate";
			public const string VendorID = "vendorid";
			public const string VendorName = "vendorname";
			public const string VendorPartNumber = "vendorpartnumber";
			public const string VersionNumber = "versionnumber";
			public const string product_incidents = "product_incidents";
			public const string Referencedproduct_parent_product = "Referencedproduct_parent_product";
			public const string product_entitlement_association = "product_entitlement_association";
			public const string Referencingproduct_parent_product = "product_parent_product";
			public const string subject_products = "subject_products";
			public const string unit_of_measurement_products = "unit_of_measurement_products";
			public const string unit_of_measurement_schedule_products = "unit_of_measurement_schedule_products";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public Product() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "product";
		
		public const string EntityLogicalCollectionName = "products";
		
		public const string EntitySetName = "products";
		
		/// <summary>
		/// Unique identifier of the user who created the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the external party who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyexternalparty")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedByExternalParty
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdbyexternalparty");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyexternalpartyname")]
		public string CreatedByExternalPartyName
		{
			get
			{
				if (this.FormattedValues.Contains("createdbyexternalparty"))
				{
					return this.FormattedValues["createdbyexternalparty"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyexternalpartyyominame")]
		public string CreatedByExternalPartyYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdbyexternalparty"))
				{
					return this.FormattedValues["createdbyexternalparty"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the product was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Current cost for the product item. Used in price calculations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currentcost")]
		public Microsoft.Xrm.Sdk.Money CurrentCost
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("currentcost");
			}
			set
			{
				this.SetAttributeValue("currentcost", value);
			}
		}
		
		/// <summary>
		/// Value of the Current Cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currentcost_base")]
		public Microsoft.Xrm.Sdk.Money CurrentCost_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("currentcost_base");
			}
		}
		
		/// <summary>
		/// Default unit for the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultuomid")]
		public Microsoft.Xrm.Sdk.EntityReference DefaultUoMId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defaultuomid");
			}
			set
			{
				this.SetAttributeValue("defaultuomid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultuomidname")]
		public string DefaultUoMIdName
		{
			get
			{
				if (this.FormattedValues.Contains("defaultuomid"))
				{
					return this.FormattedValues["defaultuomid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Default unit group for the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultuomscheduleid")]
		public Microsoft.Xrm.Sdk.EntityReference DefaultUoMScheduleId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defaultuomscheduleid");
			}
			set
			{
				this.SetAttributeValue("defaultuomscheduleid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultuomscheduleidname")]
		public string DefaultUoMScheduleIdName
		{
			get
			{
				if (this.FormattedValues.Contains("defaultuomscheduleid"))
				{
					return this.FormattedValues["defaultuomscheduleid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Description of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.SetAttributeValue("description", value);
			}
		}
		
		/// <summary>
		/// Internal Use Only
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dmtimportstate")]
		public System.Nullable<int> DMTImportState
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dmtimportstate");
			}
			set
			{
				this.SetAttributeValue("dmtimportstate", value);
			}
		}
		
		/// <summary>
		/// Shows the default image for the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.SetAttributeValue("entityimage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the product with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Hierarchy path of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("hierarchypath")]
		public string HierarchyPath
		{
			get
			{
				return this.GetAttributeValue<string>("hierarchypath");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Information that specifies whether the product is a kit.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iskit")]
		public System.Nullable<bool> IsKit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("iskit");
			}
			set
			{
				this.SetAttributeValue("iskit", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iskitname")]
		public string IsKitName
		{
			get
			{
				if (this.FormattedValues.Contains("iskit"))
				{
					return this.FormattedValues["iskit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isreparented")]
		public System.Nullable<bool> IsReparented
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isreparented");
			}
			set
			{
				this.SetAttributeValue("isreparented", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isreparentedname")]
		public string isreparentedName
		{
			get
			{
				if (this.FormattedValues.Contains("isreparented"))
				{
					return this.FormattedValues["isreparented"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Information about whether the product is a stock item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isstockitem")]
		public System.Nullable<bool> IsStockItem
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isstockitem");
			}
			set
			{
				this.SetAttributeValue("isstockitem", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isstockitemname")]
		public string IsStockItemName
		{
			get
			{
				if (this.FormattedValues.Contains("isstockitem"))
				{
					return this.FormattedValues["isstockitem"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the external party who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyexternalparty")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedByExternalParty
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedbyexternalparty");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyexternalpartyname")]
		public string ModifiedByExternalPartyName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedbyexternalparty"))
				{
					return this.FormattedValues["modifiedbyexternalparty"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyexternalpartyyominame")]
		public string ModifiedByExternalPartyYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedbyexternalparty"))
				{
					return this.FormattedValues["modifiedbyexternalparty"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the product was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Alternate name/description for product
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_alsoknownas")]
		public string msdyn_AlsoKnownAs
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_alsoknownas");
			}
			set
			{
				this.SetAttributeValue("msdyn_alsoknownas", value);
			}
		}
		
		/// <summary>
		/// Specify whether a product is to be converted to a customer asset. When a product is used on a work order, the system will automatically convert it into a customer asset when the work order is closed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_converttocustomerasset")]
		public System.Nullable<bool> msdyn_ConvertToCustomerAsset
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_converttocustomerasset");
			}
			set
			{
				this.SetAttributeValue("msdyn_converttocustomerasset", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_converttocustomerassetname")]
		public string msdyn_converttocustomerassetName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_converttocustomerasset"))
				{
					return this.FormattedValues["msdyn_converttocustomerasset"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Default vendor that supplies this product
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_defaultvendor")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_DefaultVendor
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_defaultvendor");
			}
			set
			{
				this.SetAttributeValue("msdyn_defaultvendor", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_defaultvendorname")]
		public string msdyn_DefaultVendorName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_defaultvendor"))
				{
					return this.FormattedValues["msdyn_defaultvendor"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_defaultvendoryominame")]
		public string msdyn_DefaultVendorYomiName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_defaultvendor"))
				{
					return this.FormattedValues["msdyn_defaultvendor"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_fieldserviceproducttype")]
		public virtual msdyn_fieldserviceproducttype? msdyn_FieldServiceProductType
		{
			get
			{
				return ((msdyn_fieldserviceproducttype?)(EntityOptionSetEnum.GetEnum(this, "msdyn_fieldserviceproducttype")));
			}
			set
			{
				this.SetAttributeValue("msdyn_fieldserviceproducttype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_fieldserviceproducttypename")]
		public string msdyn_fieldserviceproducttypeName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_fieldserviceproducttype"))
				{
					return this.FormattedValues["msdyn_fieldserviceproducttype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Describes whether product is opted out or not
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_gdproptout")]
		public System.Nullable<bool> msdyn_gdproptout
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_gdproptout");
			}
			set
			{
				this.SetAttributeValue("msdyn_gdproptout", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_gdproptoutname")]
		public string msdyn_gdproptoutName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_gdproptout"))
				{
					return this.FormattedValues["msdyn_gdproptout"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Type the name for the product when used on a purchase order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_purchasename")]
		public string msdyn_PurchaseName
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_purchasename");
			}
			set
			{
				this.SetAttributeValue("msdyn_purchasename", value);
			}
		}
		
		/// <summary>
		/// Different scopes that the product belongs to
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_scopes")]
		public string msdyn_scopes
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_scopes");
			}
			set
			{
				this.SetAttributeValue("msdyn_scopes", value);
			}
		}
		
		/// <summary>
		/// Select whether the item is taxable. If an item is set as not taxable, it won't be taxable even on a taxable work order.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_taxable")]
		public System.Nullable<bool> msdyn_Taxable
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_taxable");
			}
			set
			{
				this.SetAttributeValue("msdyn_taxable", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_taxablename")]
		public string msdyn_taxableName
		{
			get
			{
				if (this.FormattedValues.Contains("msdyn_taxable"))
				{
					return this.FormattedValues["msdyn_taxable"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Shows the UPC Code for product. Used for bar code scanning.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_upccode")]
		public string msdyn_UPCCode
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_upccode");
			}
			set
			{
				this.SetAttributeValue("msdyn_upccode", value);
			}
		}
		
		/// <summary>
		/// Name of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.SetAttributeValue("name", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationidname")]
		public string OrganizationIdName
		{
			get
			{
				if (this.FormattedValues.Contains("organizationid"))
				{
					return this.FormattedValues["organizationid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Specifies the parent product family hierarchy.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentproductid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentProductId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentproductid");
			}
			set
			{
				this.SetAttributeValue("parentproductid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentproductidname")]
		public string ParentProductIdName
		{
			get
			{
				if (this.FormattedValues.Contains("parentproductid"))
				{
					return this.FormattedValues["parentproductid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// List price for the product item. Used in price calculations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("price")]
		public Microsoft.Xrm.Sdk.Money Price
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("price");
			}
			set
			{
				this.SetAttributeValue("price", value);
			}
		}
		
		/// <summary>
		/// Value of the List Price in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("price_base")]
		public Microsoft.Xrm.Sdk.Money Price_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("price_base");
			}
		}
		
		/// <summary>
		/// Select the default price list for the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelid")]
		public Microsoft.Xrm.Sdk.EntityReference PriceLevelId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pricelevelid");
			}
			set
			{
				this.SetAttributeValue("pricelevelid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricelevelidname")]
		public string PriceLevelIdName
		{
			get
			{
				if (this.FormattedValues.Contains("pricelevelid"))
				{
					return this.FormattedValues["pricelevelid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Shows the ID of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
		public System.Nullable<System.Guid> ProductId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("productid");
			}
			set
			{
				this.SetAttributeValue("productid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.ProductId = value;
			}
		}
		
		/// <summary>
		/// User-defined product ID.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productnumber")]
		public string ProductNumber
		{
			get
			{
				return this.GetAttributeValue<string>("productnumber");
			}
			set
			{
				this.SetAttributeValue("productnumber", value);
			}
		}
		
		/// <summary>
		/// Product Structure.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productstructure")]
		public virtual product_productstructure? ProductStructure
		{
			get
			{
				return ((product_productstructure?)(EntityOptionSetEnum.GetEnum(this, "productstructure")));
			}
			set
			{
				this.SetAttributeValue("productstructure", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productstructurename")]
		public string ProductStructureName
		{
			get
			{
				if (this.FormattedValues.Contains("productstructure"))
				{
					return this.FormattedValues["productstructure"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Type of product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("producttypecode")]
		public virtual product_producttypecode? ProductTypeCode
		{
			get
			{
				return ((product_producttypecode?)(EntityOptionSetEnum.GetEnum(this, "producttypecode")));
			}
			set
			{
				this.SetAttributeValue("producttypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("producttypecodename")]
		public string ProductTypeCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("producttypecode"))
				{
					return this.FormattedValues["producttypecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// URL for the Website associated with the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("producturl")]
		public string ProductUrl
		{
			get
			{
				return this.GetAttributeValue<string>("producturl");
			}
			set
			{
				this.SetAttributeValue("producturl", value);
			}
		}
		
		/// <summary>
		/// Number of decimal places that can be used in monetary amounts for the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quantitydecimal")]
		public System.Nullable<int> QuantityDecimal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("quantitydecimal");
			}
			set
			{
				this.SetAttributeValue("quantitydecimal", value);
			}
		}
		
		/// <summary>
		/// Quantity of the product in stock.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quantityonhand")]
		public System.Nullable<decimal> QuantityOnHand
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("quantityonhand");
			}
			set
			{
				this.SetAttributeValue("quantityonhand", value);
			}
		}
		
		/// <summary>
		/// Product size.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("size")]
		public string Size
		{
			get
			{
				return this.GetAttributeValue<string>("size");
			}
			set
			{
				this.SetAttributeValue("size", value);
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// Standard cost for the product item. Used in price calculations.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("standardcost")]
		public Microsoft.Xrm.Sdk.Money StandardCost
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("standardcost");
			}
			set
			{
				this.SetAttributeValue("standardcost", value);
			}
		}
		
		/// <summary>
		/// Value of the Standard Cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("standardcost_base")]
		public Microsoft.Xrm.Sdk.Money StandardCost_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("standardcost_base");
			}
		}
		
		/// <summary>
		/// Status of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual product_statecode? StateCode
		{
			get
			{
				return ((product_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual product_statuscode? StatusCode
		{
			get
			{
				return ((product_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodeName
		{
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Stock volume of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stockvolume")]
		public System.Nullable<decimal> StockVolume
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("stockvolume");
			}
			set
			{
				this.SetAttributeValue("stockvolume", value);
			}
		}
		
		/// <summary>
		/// Stock weight of the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stockweight")]
		public System.Nullable<decimal> StockWeight
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("stockweight");
			}
			set
			{
				this.SetAttributeValue("stockweight", value);
			}
		}
		
		/// <summary>
		/// Select a category for the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
		public Microsoft.Xrm.Sdk.EntityReference SubjectId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("subjectid");
			}
			set
			{
				this.SetAttributeValue("subjectid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectidname")]
		public string SubjectIdName
		{
			get
			{
				if (this.FormattedValues.Contains("subjectid"))
				{
					return this.FormattedValues["subjectid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Name of the product's supplier.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("suppliername")]
		public string SupplierName
		{
			get
			{
				return this.GetAttributeValue<string>("suppliername");
			}
			set
			{
				this.SetAttributeValue("suppliername", value);
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Date from which this product is valid.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("validfromdate")]
		public System.Nullable<System.DateTime> ValidFromDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("validfromdate");
			}
			set
			{
				this.SetAttributeValue("validfromdate", value);
			}
		}
		
		/// <summary>
		/// Date to which this product is valid.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("validtodate")]
		public System.Nullable<System.DateTime> ValidToDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("validtodate");
			}
			set
			{
				this.SetAttributeValue("validtodate", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of vendor supplying the product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vendorid")]
		public string VendorID
		{
			get
			{
				return this.GetAttributeValue<string>("vendorid");
			}
			set
			{
				this.SetAttributeValue("vendorid", value);
			}
		}
		
		/// <summary>
		/// Name of the product vendor.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vendorname")]
		public string VendorName
		{
			get
			{
				return this.GetAttributeValue<string>("vendorname");
			}
			set
			{
				this.SetAttributeValue("vendorname", value);
			}
		}
		
		/// <summary>
		/// Unique part identifier in vendor catalog of this product.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vendorpartnumber")]
		public string VendorPartNumber
		{
			get
			{
				return this.GetAttributeValue<string>("vendorpartnumber");
			}
			set
			{
				this.SetAttributeValue("vendorpartnumber", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N product_incidents
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("product_incidents")]
		public System.Collections.Generic.IEnumerable<DataverseModel.Incident> product_incidents
		{
			get
			{
				return this.GetRelatedEntities<DataverseModel.Incident>("product_incidents", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseModel.Incident>("product_incidents", null, value);
			}
		}
		
		/// <summary>
		/// 1:N product_parent_product
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("product_parent_product", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DataverseModel.Product> Referencedproduct_parent_product
		{
			get
			{
				return this.GetRelatedEntities<DataverseModel.Product>("product_parent_product", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.SetRelatedEntities<DataverseModel.Product>("product_parent_product", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// N:N product_entitlement_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("product_entitlement_association")]
		public System.Collections.Generic.IEnumerable<DataverseModel.Entitlement> product_entitlement_association
		{
			get
			{
				return this.GetRelatedEntities<DataverseModel.Entitlement>("product_entitlement_association", null);
			}
			set
			{
				this.SetRelatedEntities<DataverseModel.Entitlement>("product_entitlement_association", null, value);
			}
		}
		
		/// <summary>
		/// N:1 product_parent_product
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentproductid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("product_parent_product", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DataverseModel.Product Referencingproduct_parent_product
		{
			get
			{
				return this.GetRelatedEntity<DataverseModel.Product>("product_parent_product", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.SetRelatedEntity<DataverseModel.Product>("product_parent_product", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
		
		/// <summary>
		/// N:1 subject_products
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("subject_products")]
		public DataverseModel.Subject subject_products
		{
			get
			{
				return this.GetRelatedEntity<DataverseModel.Subject>("subject_products", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseModel.Subject>("subject_products", null, value);
			}
		}
		
		/// <summary>
		/// N:1 unit_of_measurement_products
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultuomid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("unit_of_measurement_products")]
		public DataverseModel.UoM unit_of_measurement_products
		{
			get
			{
				return this.GetRelatedEntity<DataverseModel.UoM>("unit_of_measurement_products", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseModel.UoM>("unit_of_measurement_products", null, value);
			}
		}
		
		/// <summary>
		/// N:1 unit_of_measurement_schedule_products
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultuomscheduleid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("unit_of_measurement_schedule_products")]
		public DataverseModel.UoMSchedule unit_of_measurement_schedule_products
		{
			get
			{
				return this.GetRelatedEntity<DataverseModel.UoMSchedule>("unit_of_measurement_schedule_products", null);
			}
			set
			{
				this.SetRelatedEntity<DataverseModel.UoMSchedule>("unit_of_measurement_schedule_products", null, value);
			}
		}
	}
}
#pragma warning restore CS1591
