#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum entitytype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 0,
		
		/// <summary>
		/// Work Order
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WorkOrder = 192350000,
	}
}
#pragma warning restore CS1591
