#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_fieldserviceproducttype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inventory = 690970000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonInventory = 690970001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Service = 690970002,
	}
}
#pragma warning restore CS1591
