<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Reimaginate.DataHub.Agent.Dataverse'">
    <VersionPrefix>1.4.4</VersionPrefix>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Reimaginate.DataHub.Agent.TestFramework.Dataverse'">
    <VersionPrefix>1.4.4</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <DataHubAgentPublicPackage Include="Reimaginate.DataHub.Agent.Dataverse">
      <ProjectPath>src\Reimaginate.DataHub.Agent.Dataverse\Reimaginate.DataHub.Agent.Dataverse.csproj</ProjectPath>
      <Version>1.4.4</Version>
      <Family>dataverse</Family>
      <ReleaseEnabled>true</ReleaseEnabled>
      <PublicRepository>https://github.com/Reimaginate/DataHub.Agent.Dataverse</PublicRepository>
    </DataHubAgentPublicPackage>
    <DataHubAgentPublicPackage Include="Reimaginate.DataHub.Agent.TestFramework.Dataverse">
      <ProjectPath>src\Reimaginate.DataHub.Agent.TestFramework.Dataverse\Reimaginate.DataHub.Agent.TestFramework.Dataverse.csproj</ProjectPath>
      <Version>1.4.4</Version>
      <Family>dataverse</Family>
      <ReleaseEnabled>true</ReleaseEnabled>
      <PublicRepository>https://github.com/Reimaginate/DataHub.Agent.Dataverse</PublicRepository>
    </DataHubAgentPublicPackage>
  </ItemGroup>
</Project>
